### PR TITLE
add action buttons to datatable

### PR DESCRIPTION
**Pull request by mohammadgh1370**
**add multiple buttons in datatable where action
1-button with open other page
2-button with emit data to parent to show data in model
3-button with ajax request and reload datatable such delete row

**add icon sort to th table and default arrow

### CODE REVIEW

**Comment by mohammadgh1370** [comment]
hi james,
say this commit? 
its good or not?
require to change?

**Comment by mohammadgh1370** [comment]
@jamesdordoy 
please answer

**Comment by jamesdordoy** [comment]
@mohammadgh1370 apologies ill take a look at this PR shortly.

**Comment by jamesdordoy** [comment]
Hey @mohammadgh1370,

I have cloned your repo of this repository and i have run `yarn serve`.

I noticed that your changes to the API have breaking changes to the package by changing some of the default props for the table, table cell etc.

None of the examples are running due to your proposed changes to the API. So i can't merge this, as it will have breaking changes across the board for end-users and i cannot tell if your implementation will work as all of the example implementations are not working.

**Comment by mohammadgh1370** [comment]
@jamesdordoy hi james, please see this demo datatable project and write your comment, thank you

[github repository demo](https://github.com/mohammadgh1370/laravuedatatable)

[online demo](http://datatable.ihweb.ir/)

**Comment by jamesdordoy** [comment]
Im closing this PR, as i mentioned on your comment. This would be far to large of an API change to make at the moment. Please release this as a package if you are able to implement yourself.

**Pull request closed without merging**
